# Name of your site (displayed in the header)
name: Conan Chen

# URL of your avatar or profile pic
avatar: images/profile.jpg

footer-links:
  dribbble:
  email: your@email.com
  github: conancchen
  linkedin: your-linkedin-slug2
  pinterest:
  rss:
  twitter:
  stackoverflow:
  youtube:
  googleplus:

disqus:
google_analytics:

url: "https://conancchen.github.io"